name: Docker Image CI

on:
  create:
    tags:
      - '*'
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
       name: Build
       run: |
          docker build -t getcarrier/observer-lighthouse-nodejs:2.5 .
    -
       name: Push
       run: |
         docker push getcarrier/observer-lighthouse-nodejs:2.5
